spring:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false