FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /app

COPY pom.xml .
COPY infrastructure/config-service/pom.xml infrastructure/config-service/
COPY infrastructure/discovery-service/pom.xml infrastructure/discovery-service/
COPY gateway/api-gateway/pom.xml gateway/api-gateway/
COPY shared/common-core/pom.xml shared/common-core/
COPY shared/common-security/pom.xml shared/common-security/
COPY services/auth-service/pom.xml services/auth-service/
COPY services/patient-service/pom.xml services/patient-service/
COPY services/appointment-service/pom.xml services/appointment-service/
COPY services/doctor-service/pom.xml services/doctor-service/

RUN mvn -f /app/pom.xml dependency:resolve -pl services/doctor-service -am -q || true

COPY shared/common-core shared/common-core
COPY shared/common-security shared/common-security
COPY services/doctor-service services/doctor-service

RUN mvn -f /app/pom.xml clean package -pl services/doctor-service -am -DskipTests -q

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=builder /app/services/doctor-service/target/doctor-service-*.jar doctor-service.jar

EXPOSE 8003

ENV JAVA_OPTS=""


HEALTHCHECK --interval=30s --timeout=10s --retries=5 --start-period=40s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8003/actuator/health || exit 1

ENTRYPOINT ["java", "-jar", "doctor-service.jar"]
