spring:
  output:
    ansi:
      enabled: detect

logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){faint} %clr(%-5level){highlight} %clr(%logger{36}){cyan} %clr(-){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level - %logger{36} - %msg%n"
  file:
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOSTNAME:localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka/

medsync:
  security:
    secret-key: ${AUTH_SERVER_SECRET_KEY}
    access-token-expiration: ${AUTH_SERVER_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token-expiration: ${AUTH_SERVER_REFRESH_TOKEN_EXPIRATION:86400000}
    password-strength: ${AUTH_SERVER_PASSWORD_STRENGTH:10}
    client-origin: ${AUTH_SERVER_CLIENT_ORIGIN:http://localhost:3000}
  encryption:
    key: ${ENCRYPTION_KEY}
  hash:
    key: ${MEDSYNC_HASH_KEY}

app:
  bootstrap-admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
    email: ${BOOTSTRAP_ADMIN_EMAIL:}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:}