spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/v1/patients/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**
logging:
  level:
    org.springframework.cloud.gateway: INFO

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

server:
  port: ${GATEWAY_SERVER_PORT:8222}